# Generated by Django 5.2 on 2025-07-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('narxi', models.PositiveIntegerField()),
                ('rasmi', models.ImageField(upload_to='')),
                ('info', models.TextField()),
            ],
        ),
    ]
