# Generated by Django 5.2.4 on 2025-09-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_yutuq_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name="O'yin nomi")),
                ('tavsif', models.TextField(verbose_name="O'yin haqida")),
                ('rasmi', models.ImageField(upload_to='oyinlar/', verbose_name="O'yin rasmi")),
                ('link', models.URLField(max_length=500, verbose_name="O'yin havolasi")),
                ('kategoriya', models.CharField(choices=[('arkada', 'Arkada'), ('puzzle', 'Puzzle'), ('strategiya', 'Strategiya'), ('sport', 'Sport'), ('jang', 'Jang'), ('sarguzasht', 'Sarguzasht'), ('boshqa', 'Boshqa')], default='boshqa', max_length=50, verbose_name="O'yin kategoriyasi")),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('yangilangan_sana', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "O'yin",
                'verbose_name_plural': "O'yinlar",
                'ordering': ['-yaratilgan_sana'],
            },
        ),
    ]
